version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: jobs_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline
      POSTGRES_DB: airflow_meta
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: